services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: postgres
    ports:
      - "5433:5433"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
